### ISSUE TITLE
DLLNotFoundException on Linux

### ISSUE THREAD

**Issue by Todlly** [CefNet/CefNet#121]
I'm getting DLLNotFoundException from NativeMethods.dlopen method. It gets the path to cef correctly, CefNet version is 105.3.22248.142 and cef for Linux-64 version is 105.3.39 so i don't really understand what's the problem

**Comment by HeChenz** [comment]
You can try this command on your linux:
`export LD_PRELOAD=<youre_cef_release_path>/libcef.so:$LD_PRELOAD`

if you don't want set everytime, can write to the end of file ~/.bashrc

**Comment by Haltroy** [comment]
You guys are talking about this error, right?

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at CefNet.NativeMethods.dlopen(String path, Int32 mode)
   at CefNet.CefNetApplication.Initialize(String path, CefSettings settings)
```

Well, I also get that. I also tried `export LD_PRELOAD=<youre_cef_release_path>/libcef.so:$LD_PRELOAD` thing and the `LD_DEBUG=liblibdl` (as the message said) but both did nothing. I also added `libdl.so` to the `LD_PRELOAD` and copied libdl.so to both my executable and CEF folder. Still, no luck.

I did some digging and found `libdl` in a package that I already installed (`glibc` in Arch Linux) and does exists in the file system (as `/usr/lib/libdl.so.2`).

So I decided to make a symbolic link to `/usr/lib/libdl.so` which points to `/usr/lib/libdl.so.2` and after that, this error showed up:

```
[1111/111324.205502:ERROR:zygote_communication_linux.cc(142)] Did not receive ping from zygote child
[1111/111324.205856:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[1111/111324.205881:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 1 time(s)
[1111/111324.206963:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[1111/111324.206988:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 2 time(s)
[1111/111324.207687:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[1111/111324.207708:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 3 time(s)
[1111/111324.208492:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[1111/111324.208514:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 4 time(s)
[1111/111324.209309:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[1111/111324.209360:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 5 time(s)
[1111/111324.210042:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[1111/111324.210058:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 6 time(s)
[1111/111324.211039:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[1111/111324.211091:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 7 time(s)
[1111/111324.211812:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[1111/111324.211846:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 8 time(s)
[1111/111324.212792:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[1111/111324.212856:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 9 time(s)
[1111/111324.212929:FATAL:gpu_data_manager_impl_private.cc(454)] GPU process isn't usable. Goodbye.
```

I kinda fixed it by disabling MultiThreadedMessageLoop but it didn't showed up any single Avalonia window and have no idea why and I'm lost at this point.

**Comment by HeChenz** [comment]
> You guys are talking about this error, right?
> 
> ```
> Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
>    at CefNet.NativeMethods.dlopen(String path, Int32 mode)
>    at CefNet.CefNetApplication.Initialize(String path, CefSettings settings)
> ```
> 
> Well, I also get that. I also tried `export LD_PRELOAD=<youre_cef_release_path>/libcef.so:$LD_PRELOAD` thing and the `LD_DEBUG=liblibdl` (as the message said) but both did nothing. I also added `libdl.so` to the `LD_PRELOAD` and copied libdl.so to both my executable and CEF folder. Still, no luck.
> 
> I did some digging and found `libdl` in a package that I already installed (`glibc` in Arch Linux) and does exists in the file system (as `/usr/lib/libdl.so.2`).
> 
> So I decided to make a symbolic link to `/usr/lib/libdl.so` which points to `/usr/lib/libdl.so.2` and after that, this error showed up:
> 
> ```
> [1111/111324.205502:ERROR:zygote_communication_linux.cc(142)] Did not receive ping from zygote child
> [1111/111324.205856:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.205881:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 1 time(s)
> [1111/111324.206963:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.206988:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 2 time(s)
> [1111/111324.207687:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.207708:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 3 time(s)
> [1111/111324.208492:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.208514:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 4 time(s)
> [1111/111324.209309:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.209360:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 5 time(s)
> [1111/111324.210042:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.210058:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 6 time(s)
> [1111/111324.211039:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.211091:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 7 time(s)
> [1111/111324.211812:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.211846:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 8 time(s)
> [1111/111324.212792:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.212856:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 9 time(s)
> [1111/111324.212929:FATAL:gpu_data_manager_impl_private.cc(454)] GPU process isn't usable. Goodbye.
> ```
> 
> I kinda fixed it by disabling MultiThreadedMessageLoop but it didn't showed up any single Avalonia window and have no idea why and I'm lost at this point.

May be your system not support GPU?

**Comment by Haltroy** [comment]
> May be your system not support GPU?

Ah yes, the Intel UHD Graphics 630, the only GPU that can open Chrome and other Chromium programs and CEF simple application but not a C# program that uses the same CEF library that the simple application uses. Or its because of Nvidia GTX 1650 Mobile. Anyways jokes aside, I don't think its because of the GPU.

I'm might be missing something because after disabling the same setting, it just didn't initialized the browser on Windows.

So what I think is happening is that I'm missing something (either a package or a line of code in my app) that makes CEF can't talk (*Message*) to other threads (*MultiThreaded*) that also run CEF at that time (*Loop*). And disabling this feature lets CEF run but not powerful enough to show something working. I might be wrong but currently that's what I can see for now.

SO, I added some of the code from AvaloniaApp\Program.cs file and now it just shows up the window for a time and then app shuts down for no reason at all without displaying the browser content. No messages, no errors. 

Totally lost on this, now in both Windows and Linux.

**Comment by AlexanderDotH** [comment]
> You guys are talking about this error, right?
> 
> ```
> Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
>    at CefNet.NativeMethods.dlopen(String path, Int32 mode)
>    at CefNet.CefNetApplication.Initialize(String path, CefSettings settings)
> ```
> 
> Well, I also get that. I also tried `export LD_PRELOAD=<youre_cef_release_path>/libcef.so:$LD_PRELOAD` thing and the `LD_DEBUG=liblibdl` (as the message said) but both did nothing. I also added `libdl.so` to the `LD_PRELOAD` and copied libdl.so to both my executable and CEF folder. Still, no luck.
> 
> I did some digging and found `libdl` in a package that I already installed (`glibc` in Arch Linux) and does exists in the file system (as `/usr/lib/libdl.so.2`).
> 
> So I decided to make a symbolic link to `/usr/lib/libdl.so` which points to `/usr/lib/libdl.so.2` and after that, this error showed up:
> 
> ```
> [1111/111324.205502:ERROR:zygote_communication_linux.cc(142)] Did not receive ping from zygote child
> [1111/111324.205856:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.205881:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 1 time(s)
> [1111/111324.206963:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.206988:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 2 time(s)
> [1111/111324.207687:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.207708:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 3 time(s)
> [1111/111324.208492:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.208514:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 4 time(s)
> [1111/111324.209309:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.209360:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 5 time(s)
> [1111/111324.210042:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.210058:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 6 time(s)
> [1111/111324.211039:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.211091:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 7 time(s)
> [1111/111324.211812:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.211846:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 8 time(s)
> [1111/111324.212792:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
> [1111/111324.212856:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 9 time(s)
> [1111/111324.212929:FATAL:gpu_data_manager_impl_private.cc(454)] GPU process isn't usable. Goodbye.
> ```
> 
> I kinda fixed it by disabling MultiThreadedMessageLoop but it didn't showed up any single Avalonia window and have no idea why and I'm lost at this point.

I also tried it and could not fix it

**Comment by Haltroy** [comment]
I just tried running the AvaloniaApp by detaching it from the rest of the solution and adding CefNet packages by NuGet and somehow it worked. I have no idea why but it did work. It even run with `MultiThreadedMessageLoop` as default.

Then I deleted my `libdl.so` symbolic link and it went back to square one. Which means my temporary solution to `libdl` is working. `sudo ln -sf /usr/lib/libdl.so.2 /usr/lib/libdl.so` ((NOTE: If the libdl.so does exist in that folder, don't attempt. Also notice the `.2` at the end of it, it might be different in your case so check it with `ls /usr/lib | grep libdl.so`)) ((The one-liner that worked in my case: `sudo ln -sf /usr/lib/$(ls /usr/lib/ | grep libdl.so) /usr/lib/libdl.so`)). The problem was `libdl` did exist but under a different file name `libdl.so.2` instead of just `libdl.so`.

So, I'm currently at lost on why it worked on `AvaloniaApp` but not on the exact same copy-pasted code in my project. I think there's some stuff that we didn't implement that made the "GPU process crashed" a thing. Also noticed the Avalonia looks different on the AvaloniaApp.

**Comment by Haltroy** [comment]
Good thing that GitHub automatically added the "mention" thing. Looks like my problems are getting off-topic. So, I'm no longer going to comment here. If you are having the same problems, just follow that but for now, the temporary fix for this is to install glibc package and creating a symbolic link if the file name is not `libdl.so` with: `sudo ln -sf /usr/lib/$(ls /usr/lib/ | grep libdl.so) /usr/lib/libdl.so`
Of course, for professional packaging, I recommend putting the `libdl.so` to your package so users don't have to run that command every time.Either the library itself or a symbolic link that links to that library or run the one-liner command after extract ((some package managers have that feature afaik)). idk go crazy with it.

**Comment by haydenwsw** [comment]
I had this issue on linux so i'll paste all my trouble shooting

System.DllNotFoundException: Can't load '<youre_cef_release_path>/libcef.so
`export LD_PRELOAD=<youre_cef_release_path>/libcef.so:$LD_PRELOAD`
if you don't want set everytime, add to the end of file ~/.profile

System.DllNotFoundException: Unable to load shared library 'libdl'
`whereis libdl.so.2`
`sudo ln -sf <your_libdl.so.2_path> /usr/lib/libdl.so`

System.DllNotFoundException: Unable to load shared library 'X11'
`sudo apt-get install libx11-dev`

for this error:
```
[0318/222554.559648:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[0318/222554.561052:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 1 time(s)
[0318/222554.676548:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[0318/222554.676855:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 2 time(s)
[0318/222554.691212:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[0318/222554.691500:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 3 time(s)
[0318/222554.696591:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[0318/222554.696880:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 4 time(s)
[0318/222554.701116:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[0318/222554.701495:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 5 time(s)
[0318/222554.710597:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[0318/222554.710823:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 6 time(s)
[0318/222554.716608:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[0318/222554.716810:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 7 time(s)
[0318/222554.721100:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[0318/222554.721237:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 8 time(s)
[0318/222554.724760:ERROR:gpu_process_host.cc(959)] GPU process launch failed: error_code=1002
[0318/222554.724884:WARNING:gpu_process_host.cc(1267)] The GPU process has crashed 9 time(s)
[0318/222554.725015:FATAL:gpu_data_manager_impl_private.cc(454)] GPU process isn't usable. Goodbye.
```
you need add this code to your application can be found in /WinFormsCoreApp/CefAppImpl.cs
```cs
public class CefAppImpl : CefNetApplication
{
    protected override void OnBeforeCommandLineProcessing(string processType, CefCommandLine commandLine)
    {
        base.OnBeforeCommandLineProcessing(processType, commandLine);

        if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
        {
            commandLine.AppendSwitch("no-zygote");
            commandLine.AppendSwitch("no-sandbox");
        }
    }
}
```

**Comment by Haltroy** [comment]
Created a repository with 2 examples (one from this repository itself, other is a MVVM app example) and they both work on Linux. There's also documentation which notes [these findings](https://github.com/CefNet/CefNet/issues/121#issuecomment-1474819158) on the README.md file.
https://github.com/Haltroy/CefNet.Avalonia.Examples
