### ISSUE TITLE
System.EntryPointNotFoundException:“Unable to find an entry point named 'SetWindowLongPtr' in DLL 'user32.dll'.”

### ISSUE THREAD

**Issue by neostfox** [CefNet/CefNet#20]
On X86 Platform has this error

**Comment by vmas** [comment]
What is the stack trace for the exception?

**Comment by neostfox** [comment]
![image](https://user-images.githubusercontent.com/28594168/89861822-3d3cc380-dbd9-11ea-837e-d1a9c09ab216.png)
I only can see this. can't font any  stack trace.

**Comment by neostfox** [comment]
I got it.
   at CefNet.WinApi.NativeMethods.SetWindowLongPtr(IntPtr hWnd, Int32 nIndex, IntPtr dwNewLong)
   at CefNet.Internal.WindowsHwndSource.FromHwnd(IntPtr hwnd)
   at CefNet.Internal.GlobalHooks.TryAddGlobalHook(Window window)
   at CefNet.Internal.GlobalHooks.Initialize(WebView view)
   at CefNet.Avalonia.WebView.OnInitialized()
   at Avalonia.StyledElement.InitializeIfNeeded()
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Visual.SetVisualParent(Visual value)
   at Avalonia.Visual.VisualChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index)
   at Avalonia.Collections.AvaloniaList`1.Add(T item)
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild()
   at Avalonia.Controls.Presenters.ContentPresenter.ContentChanged(AvaloniaPropertyChangedEventArgs e)
   at Avalonia.Controls.Presenters.ContentPresenter.<>c.<.cctor>b__14_0(ContentPresenter x, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass7_0`1.<AddClassHandler>b__0(AvaloniaPropertyChangedEventArgs e)
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 34
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 146
   at Avalonia.AvaloniaProperty.NotifyChanged(AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.PriorityValueChanged(AvaloniaProperty property, Int32 priority, Object oldValue, Object newValue)
   at Avalonia.ValueStore.Changed(AvaloniaProperty property, Int32 priority, Object oldValue, Object newValue)
   at Avalonia.PriorityValue.SetAndNotify(ValueTuple`2& backing, ValueTuple`2 update)
   at Avalonia.PriorityValue.Avalonia.Utilities.ISetAndNotifyHandler<(System.Object,System.Int32)>.HandleSetAndNotify(AvaloniaProperty property, ValueTuple`2& backing, ValueTuple`2 value)
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotifyCallback[TValue](AvaloniaProperty property, ISetAndNotifyHandler`1 setAndNotifyHandler, TValue& backing, TValue value)
   at Avalonia.PriorityValue.UpdateValue(Object value, Int32 priority)
   at Avalonia.PriorityValue.LevelValueChanged(PriorityLevel level)
   at Avalonia.PriorityLevel.Changed(PriorityBindingEntry entry)
   at Avalonia.PriorityBindingEntry.<System.IObserver<System.Object>.OnNext>g__Signal|24_0(PriorityBindingEntry instance, Object newValue)
   at Avalonia.PriorityBindingEntry.System.IObserver<System.Object>.OnNext(Object value)
   at Avalonia.Reactive.SingleSubscriberObservableBase`1.PublishNext(T value)
   at Avalonia.Data.TemplateBinding.PublishValue()
   at Avalonia.Data.TemplateBinding.TemplatedParentPropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.PriorityValueChanged(AvaloniaProperty property, Int32 priority, Object oldValue, Object newValue)
   at Avalonia.ValueStore.Changed(AvaloniaProperty property, Int32 priority, Object oldValue, Object newValue)
   at Avalonia.ValueStore.AddValue(AvaloniaProperty property, Object value, Int32 priority)
   at Avalonia.AvaloniaObject.SetStyledValue(AvaloniaProperty property, Object value, BindingPriority priority)
   at Avalonia.AvaloniaObject.SetValue(AvaloniaProperty property, Object value, BindingPriority priority)
   at Avalonia.AvaloniaObject.SetValue[T](AvaloniaProperty`1 property, T value, BindingPriority priority)
   at Avalonia.Controls.TabControl.set_SelectedContent(Object value)
   at Avalonia.Controls.TabControl.UpdateSelectedContent(IContentControl item)
   at Avalonia.Controls.TabControl.UpdateSelectedContent(AvaloniaPropertyChangedEventArgs e)
   at Avalonia.Controls.TabControl.<>c.<.cctor>b__7_0(TabControl x, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass7_0`1.<AddClassHandler>b__0(AvaloniaPropertyChangedEventArgs e)
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 34
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 146
   at Avalonia.AvaloniaProperty.NotifyChanged(AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.Controls.Primitives.SelectingItemsControl.UpdateSelectedItem(Int32 index, Boolean clear)
   at Avalonia.Controls.Primitives.SelectingItemsControl.set_SelectedIndex(Int32 value)
   at Avalonia.Controls.Primitives.SelectingItemsControl.ItemsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.NotifyCollectionChangedExtensions.<>c__DisplayClass1_0.<WeakSubscribe>b__0(NotifyCollectionChangedEventArgs e)
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 34
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Collections.NotifyCollectionChangedExtensions.WeakCollectionChangedObservable.OnEvent(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Utilities.WeakSubscriptionManager.Subscription`1.OnEvent(Object sender, T eventArgs)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index)
   at Avalonia.Collections.AvaloniaList`1.Add(T item)
   at Unipus.Client.MainWindow.AddTab(Boolean useGlobalContext) in C:\Users\neost\source\repos\Solution1\Unipus.Client\MainWindow.xaml.cs:line 56
   at Unipus.Client.MainWindow.MainWindow_Opened(Object sender, EventArgs e) in C:\Users\neost\source\repos\Solution1\Unipus.Client\MainWindow.xaml.cs:line 45
   at Avalonia.Controls.TopLevel.OnOpened(EventArgs e)
   at Avalonia.Controls.Window.Show()
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Unipus.Client.Program.Main(String[] args) in C:\Users\neost\source\repos\Solution1\Unipus.Client\Program.cs:line 33
