### ISSUE TITLE
Incompatible input locale

### ISSUE THREAD

**Issue by neostfox** [CefNet/CefNet#21]
When i input Chinese  throw error incompatible input locale.
   at CefNet.Input.KeycodeConverter.CharacterToVirtualKey(Char character)
   at CefNet.Avalonia.WebView.OnTextInput(TextInputEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__25_4(InputElement x, TextInputEventArgs e)
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 36
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at CefNet.WinApi.NativeMethods.CallWindowProc(IntPtr lpPrevWndFunc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at CefNet.Internal.WindowsHwndSource.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Unipus.Client.Program.Main(String[] args) in C:\Users\neost\source\repos\Solution1\Unipus.Client\Program.cs:line 36

**Comment by AigioL** [comment]
@neostfox  Current solutions.
https://github.com/SteamTools-Team/SteamTools/blob/997f9f928232dee8f44808bd671bdc91787942db/src/ST.Client.Desktop.Avalonia/Application/UI/CefNetApp.cs#L171
https://github.com/SteamTools-Team/SteamTools/blob/997f9f928232dee8f44808bd671bdc91787942db/src/ST.Client.Desktop.Avalonia/Application/UI/CefNetApp.cs#L254-L282

**Comment by neostfox** [comment]
> @neostfox Current solutions.
> https://github.com/SteamTools-Team/SteamTools/blob/997f9f928232dee8f44808bd671bdc91787942db/src/ST.Client.Desktop.Avalonia/Application/UI/CefNetApp.cs#L171
> https://github.com/SteamTools-Team/SteamTools/blob/997f9f928232dee8f44808bd671bdc91787942db/src/ST.Client.Desktop.Avalonia/Application/UI/CefNetApp.cs#L254-L282

I will give my solution  tomorrow
