### ISSUE TITLE
CEF crashes on MacOS in CefFrame::GetScriptableObjectAsync

### ISSUE THREAD

**Issue by vmas** [CefNet/CefNet#59]
Sorry, maybe this Warning is not the actual error. In fact, it broke at `await frame.GetScriptableObjectAsync(cancellationToken)`
This crash just happens on Mac by the way.

Exception msg
>The method or operation is not implemented.
   at CefNet.JSInterop.ScriptableRequestInfo.GetResult()
   at CefNet.JSInterop.ScriptableObjectProvider.GetGlobal(CefFrame frame)
   at CefNet.JSInterop.ScriptableObjectProvider.GetGlobal()
   at CefNet.JSInterop.V8Extensions.GetScriptableObject(CefFrame frame)
   at CefNet.JSInterop.V8Extensions.<>c__DisplayClass0_0.<GetScriptableObjectAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at GetSharedSS.Views.MainWindow.GetSourceAsync() in G:\Visual Studio 2019\GetSharedSS\GetSharedSS\Views\MainWindow.axaml.cs:line 203
   at GetSharedSS.Views.MainWindow.ExtractAccount(Int32 delay) in G:\Visual Studio 2019\GetSharedSS\GetSharedSS\Views\MainWindow.axaml.cs:line 244

_Originally posted by @hopeko in https://github.com/CefNet/CefNet/discussions/56#discussioncomment-419870_

**Comment by vmas** [comment]
RefCountedWrapperStruct and V8ValueImplLayout have a different field layout than on Windows.

**Comment by vmas** [comment]
The MSVC compiler creates 2 virtual tables: v8value_vtable and refcounted_vtable. Others - only one.
This bug is also reproduced on Linux.

**Comment by vmas** [comment]
Fixed in cebfb68 and 9563aab
